### ISSUE TITLE
to get event click on navigation arrow with @click is not working

### ISSUE THREAD

**Issue by fewm** [ismail9k/vue3-carousel#139]
**Describe the bug**
my code is :
```
...
<template #addons>
       <Navigation @click="navigationClick" />
</template>
...

<script>
...
  methods: {
    navigationClick () {
          console.log('navigation clicked')
    }
  }
...
</script>
```
problem is that console message not showing its mean @click not trigerd ?
any solution here ?
thanks.

**To Reproduce**
1. access the page
2. click arrow navigation
3. the console not showing

**Comment by ismail9k** [comment]
By default `Navigation` component will not emit *click* event. Can you explain more on the use case you want this, so I can help you more, or introduce a new feature?

**Comment by sejanH** [comment]
If we need to make our custom pagination instead of the given buttons. How to get the click event so I can call slideTo() method?
![2022-01-16_00-23](https://user-images.githubusercontent.com/16546092/149633419-ab27773a-9db5-4c98-b9ff-b67326b74f42.png)
added the custom navigation design. I can get the clicked index from `currentSlide` but cannot access the the method slideTo() so I can't navigate to my desired slide @ismail9k
