### ISSUE TITLE
Example on website: border radius not applied while transitioning

### ISSUE THREAD

**Issue by louwers** [ismail9k/vue3-carousel#267]
For me while transitioning, the border radius is not applied.

https://user-images.githubusercontent.com/649392/209109349-e49148f6-7049-4f32-a284-4515018c19af.mp4

**Comment by ismail9k** [comment]
I don't think this is an issue, this happens because of the visible area of the view box. This is how the carousel looks like during the animation...
<img width="1021" alt="CleanShot 2022-12-27 at 11 26 59@2x" src="https://user-images.githubusercontent.com/11035467/209636777-5ae48e08-1d80-4fc3-bae2-ec8cf164c8bd.png">
