### ISSUE TITLE
different nav arrow styling on each carousel

### ISSUE THREAD

**Issue by RifkiEr24** [ismail9k/vue3-carousel#28]
I have like 3 carousel in one page on my website, and from that 3 carousel, it have each different bg and position styling, i wonder if i can add my own class on the button tag?

**Comment by ismail9k** [comment]
You can check this issue on how to customize the Navigation addon #17.
If you want advanced control, you can create your own custom navigation component, and use it instead of the currently shipped with the carousel. check the [Navigation](https://github.com/ismail9k/vue3-carousel/blob/master/src/components/Navigation.ts) component source code for this. ;)
