### ISSUE TITLE
Incorrect Slide CSS Offset Calculation after Parent Element Scaling

### ISSUE THREAD

**Issue by zjlssc** [ismail9k/vue3-carousel#321]
**Describe the bug**
The offset calculation of content items is incorrect when the parent element is scaled.

**To Reproduce**

1. Set any scaling factor for the parent element, for example, transform: scale(0.68958, 0.68958).
2. Observe the positioning error in the slide content. 

**Expected behavior**
![image](https://github.com/ismail9k/vue3-carousel/assets/10934551/6901078f-b54f-4159-9a49-c08c1dfe3c58)

**Screenshots**
![image](https://github.com/ismail9k/vue3-carousel/assets/10934551/09391ecf-fca9-48a1-b714-0536974b4cd8)

**Desktop (please complete the following information):**

- OS: [e.g. Intel Mac OS X 10_15_7]
- Browser [chrome]
- Version [e.g. 0.3.1]

**Comment by shaunrainer** [comment]
Having the same issue? any update on this?

**Comment by ismail9k** [comment]
The calculation of the slides' width is now based on the viewport element instead of the parent element. This change was implemented [here](https://github.com/ismail9k/vue3-carousel/pull/423/files#diff-dc30c5fcf494b5db78d9e9193cb3ea7698c263c1671591c7d69bbdcabfc77ca1R128). This modification should address the issue.
