### ISSUE TITLE
carousel items are displaying as individual items

### ISSUE THREAD

**Issue by viswasakthi3** [ismail9k/vue3-carousel#356]
**Describe the bug**
many times  the items which are images are showed separately as individual items 
**To Reproduce**

1. use the vue3-carousel and pass images 
**Expected behavior**
a normal carousel 
**Screenshots**
added 
**Desktop (please complete the following information):**

- OS: [windows]
- Browser [ chrome, firefox]
- Version [latest]

**Additional context**
 i thought it was constrain mismatch but its not the pblm i cant see any error in the conoso
![error eg 1](https://github.com/ismail9k/vue3-carousel/assets/75746090/b79a9f2c-6261-4175-8384-c6f6c56c0391)
![error eg 2](https://github.com/ismail9k/vue3-carousel/assets/75746090/bb18f393-6db9-4b6e-a252-61da5aca5094)
le log

**Comment by ismail9k** [comment]
Hey @viswasakthi3, I can see that there's a problem with loading the carousel stylesheet file. Please make sure that you have correctly included the `carousel.css` file. If you are using PurgeCSS or similar tools, make sure to whitelist the carousel classes.

If you are still facing the issue, please provide me with a minimal working example that reproduces the issue so that I can further debug it.

**Comment by yethuku** [comment]
i used nuxt 3,yeah the carousel.css was the issue causing that , problem solved after using this https://nuxt.com/modules/vue3-carousel-nuxt

**Comment by avpuchkova** [comment]
@yethuku Could you please show me an example how you use "vue3-carousel-nuxt"? I try to do it, but it does not work #361.

**Comment by viswasakthi3** [comment]
> @yethuku Could you please show me an example how you use "vue3-carousel-nuxt"? I try to do it, but it does not work #361.

i just installed it and it worked fine sry for the late reply
