### ISSUE TITLE
Dragging slides (swipe) with mouse fires click event.

### ISSUE THREAD

**Issue by mkyoon** [ismail9k/vue3-carousel#375]
**Describe the bug**
After upgrade to v0.3.3,
dragging slides (swipe) with mouse fires click event.

**To Reproduce**

1. Go to '[https://codesandbox.io/p/sandbox/vue3-carousel-example-01-forked-k2m47s](https://codesandbox.io/p/sandbox/vue3-carousel-example-01-forked-k2m47s)'
2. Drag with mouse on 'Carousel'
3. After dragging, window opens 'google.com'

**Expected behavior**
v.0.3.3 : Dragging with mouse is just swipes slides. Not capturing click events.
v0.3.1 : Everything is OK.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10, macOS 14
- Browser : chrome, safari (desktop)
- Version : latest

**Comment by mkyoon** [comment]
Using 'isSliding' data, I could solve this issue.

@slide-start="isSliding = true"
@slide-end="isSliding = false"

Is there any clever way to bypass this click events?

**Comment by Chambo015** [comment]
same problem

**Comment by mkyoon** [comment]
I found this comments, and it works like a charm.
https://github.com/ismail9k/vue3-carousel/issues/343#issuecomment-1852732552

**Comment by Tofandel** [comment]
I can see this library is trying to prevent the event from firing but in a wrong way, it uses a form of .stopPropagation but only when the event has already reached window

https://github.com/ismail9k/vue3-carousel/blob/master/src/components/Carousel.ts#L225-L228

This will indeed not prevent a click from firing and it should instead run event.preventDefault() instead of trying to capture the event
